language: csharp
dist: trusty
mono: none
dotnet: 2.0.0

# We need to install the .NET Core 1.0 runtime to run netcoreapp1.0
addons:
  apt:
    sources:
    - sourceline: 'deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-trusty-prod trusty main'
      key_url: 'https://packages.microsoft.com/keys/microsoft.asc'
    packages:
    - dotnet-sharedframework-microsoft.netcore.app-1.1.2

git:
  depth: 3

script:
  - build/travis.sh --quiet verify